version: '3.8'

services:
  api_backend:
    build: .
    container_name: puf_api
    ports:
      - "8001:8000"
    environment:
      # MongoDB Atlas Connection String (PUF Cluster)
      - MONGO_URL=mongodb+srv://frazliaqat1116_db_user:Teddycat54321%40@puf.74kesus.mongodb.net/?retryWrites=true&w=majority&appName=PUF
    restart: always
