version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: puf_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api_backend:
    build: .
    container_name: puf_api
    ports:
      - "8001:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/
    restart: always

volumes:
  mongo_data:
